version: '3.9'

services:
    laravel:
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
#        volumes:
#            -   ".:/app/"
        ports:
            -   8000:8000
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: mysql:5
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10


