<?php

namespace Tests\Feature;

// use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Producto;
use App\Models\Tienda;
use Tests\TestCase;


class TiendaApiTest extends TestCase
{
    private $name = '';
    public function setUp(): void
    {
        $this->name = 'test-' . time();
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function test_the_api_crud(): void
    {
        $nombre = 'test-' . time();
        $response = $this->get('/api/tiendas');
        $response->assertJsonIsArray();
        $response = $this->post('/api/tiendas', [
            'nombre' => $nombre,
            'productos' => [ ['nombre' => $this->name, 'cantidad' => 3] ]
        ]);
        $result = json_decode($response->getContent(), true);
        $this->assertIsArray($result);
        $this->assertIsInt($result['id']);
        $this->assertEquals(3, $result['productos']);
        $id = $result['id'];
        $response = $this->patch('/api/tiendas/' . $id, [
            'nombre' => $this->name,
            'productos' => [ ['nombre' => $this->name, 'cantidad' => 5] ]
        ]);
        $responseData = json_decode($response->getContent(),true);
        $this->assertEquals(['id' => $id, 'nombre' => $this->name, 'productos' => 5], $responseData );
        $response = $this->delete('/api/tiendas/' . $id);
        $responseData = json_decode($response->getContent(),true);
        $this->assertEquals('1', $responseData['rowsAffected']);
    }
    public function tearDown(): void
    {
        // This also can fail if the model is not functional leaving trailing records after test
        // ... as long as it's on dev DB it's not a big deal.
        $t = Tienda::where('nombre', $this->name)->take(1)->get()[0] ?? null;
        if ($t instanceof Tienda) {
            $t->productos()->detach();
            $t->delete();
        }
        $p = Producto::where('nombre', $this->name)->take(1)->get()[0] ?? null;
        if ($p instanceof Producto) {
            $p->tiendas()->detach();
            $p->delete();
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}


